import { randomId, randomQuantity } from '@mui/x-data-grid-generator';

const pagesTemplates = [
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
	{
		tittle: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
		language: 'PT',
		views: randomQuantity(),
		id: randomId(),
	},
];

export default pagesTemplates;
