import {
	randomCreatedDate,
	randomTraderName,
	randomId,
	randomEmail,
	randomBoolean,
} from '@mui/x-data-grid-generator';

const users = [
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: randomBoolean(),
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		email: randomEmail(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
];

export default users;
