import { randomCreatedDate, randomTraderName, randomId } from '@mui/x-data-grid-generator';

const users = [
	{
		isAdmin: false,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: false,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: false,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: false,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: false,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
	{
		isAdmin: true,
		name: randomTraderName(),
		id: randomId(),
		firstDate: randomCreatedDate(),
		func: {
			func1: true,
			func2: true,
			func3: true,
			func4: true,
			func5: true,
		},
	},
];

export default users;
