import { randomCurrency, randomPrice, randomId } from '@mui/x-data-grid-generator';

const moedas = [
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},

	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
	{
		id: randomId(),
		name: 'REAL',
		cod: randomCurrency(),
		symbol: 'afa',
		royalties: 12,
		value: randomPrice(),
		indication: 2,
		func: {
			finc1: true,
			finc2: true,
			finc3: true,
			finc4: true,
		},
	},
];

export default moedas;
